# Generated by Django 4.1.7 on 2023-11-16 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RestoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100)),
                ('image', models.CharField(default='', max_length=500)),
                ('description', models.CharField(default='', max_length=500)),
                ('price', models.CharField(default='', max_length=100)),
                ('rating', models.CharField(default='', max_length=100)),
                ('available', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
